from repositories.grades import GradesRepository
from repositories.user import UserRepository
from repositories.many_users import ManyUsersRepository
from repositories.phrases import PhrasesRepository
from repositories.settings import SettingsRepository
from repositories.requests import RequestsRepository
