from repositories.grades import GradesRepository
from repositories.user import UserRepository
from repositories.many_users import ManyUsersRepository
from repositories.phrases import PhrasesRepository
